<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.6                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2014                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2014
 *
 * Generated from xml/schema/CRM/Connectors/ConnectorType.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_Connectors_DAO_ConnectorType extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   */
  static $_tableName = 'civicrm_connector_type';
  /**
   * static instance to hold the field values
   *
   * @var array
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   */
  static $_log = false;
  /**
   * Connector Type ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Connector Type name (default for creating a new connector)
   *
   * @var string
   */
  public $name;
  /**
   * Connector Type description (default for creating a new connector)
   *
   * @var string
   */
  public $description;
  /**
   * Is this the default connector of this type for this domain?
   *
   * @var boolean
   */
  public $is_active;
  /**
   * Key of the module or extension?
   *
   * @var text
   */
  public $module;
  /**
   * Sub-function see README for examples
   *
   * @var text
   */
  public $function;
  /**
   * Plugin - see README for examples
   *
   * @var text
   */
  public $plugin;
  /**
   * Permissions in json - see README for examples
   *
   * @var text
   */
  public $permissions;
  /**
   * Is this the default connector for this module?
   *
   * @var boolean
   */
  public $is_default;

  /**
   * Label for storage field 1
   *
   * @var string
   */
  public $field1_label;
  /**
   * Label for storage field 2
   *
   * @var string
   */
  public $field2_label;
  /**
   * Label for storage field 3
   *
   * @var string
   */
  public $field3_label;
  /**
   * Label for storage field 4
   *
   * @var string
   */
  public $field4_label;
  /**
   * Label for storage field 5
   *
   * @var test
   */
  public $field5_label;
  /**
   * class constructor
   *
   * @return civicrm_connector_type
   */
  function __construct()
  {
    $this->__table = 'civicrm_connector_type';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns()
  {
    if (!self::$_links) {
      self::$_links = static ::createReferenceColumns(__CLASS__);
    }
    return self::$_links;
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Connector Type ID',
          'required' => true,
        ) ,
        'name' => array(
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Name') ,
          'description' => 'Connector Type name (default for creating a new connector)',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
        ) ,
        'description' => array(
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Description') ,
          'description' => 'Connector Type description (default for creating a new connector)',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'is_active' => array(
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Is this connector type active?',
          'required' => TRUE,
          'default' => 1,
        ) ,
        'module' => array(
          'name' => 'module',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Module') ,
          'description' => 'Key of the module or extension?',
        ) ,
        'function' => array(
          'name' => 'function',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Function') ,
          'description' => 'Module function see README for examples',
        ) ,
        'plugin' => array(
          'name' => 'plugin',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Plugin') ,
          'description' => 'Plugin - see README for examples',
        ) ,
        'permissions' => array(
          'name' => 'permissions',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Permissions') ,
          'description' => 'Permissions in json - see README for examples',
        ) ,
        'is_default' => array(
          'name' => 'is_default',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Is this the default connector for this module?',
          'required' => TRUE,
          'default' => 0,
        ) ,
        'field1_label' => array(
          'name' => 'field1_label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field1 Label') ,
          'description' => 'Label for storage field 1',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field2_label' => array(
          'name' => 'field2_label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field2 Label') ,
          'description' => 'Label for storage field 2',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field3_label' => array(
          'name' => 'field3_label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field3 Label') ,
          'description' => 'Label for storage field 3',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field4_label' => array(
          'name' => 'field4_label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field4 Label') ,
          'description' => 'Label for storage field 4',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field5_label' => array(
          'name' => 'field5_label',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Field5') ,
          'description' => 'Label for storage field 5',
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'is_active' => 'is_active',
        'module' => 'module',
        'function' => 'function',
        'plugin' => 'plugin',
        'permissions' => 'permissions',
        'is_default' => 'is_default',
        'field1_label' => 'field1_label',
        'field2_label' => 'field2_label',
        'field3_label' => 'field3_label',
        'field4_label' => 'field4_label',
        'field5_label' => 'field5_label',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['connector_type'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['connector_type'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
