<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.6                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2014                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2014
 *
 * Generated from xml/schema/CRM/Connectors/Connector.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_Connectors_DAO_Connector extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   */
  static $_tableName = 'civicrm_connector';
  /**
   * static instance to hold the field values
   *
   * @var array
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   */
  static $_log = false;
  /**
   * Connector ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * Optional FK to Domain ID
   *
   * @var int unsigned
   */
  public $domain_id;
  /**
   * Connector name (by front end user)
   *
   * @var string
   */
  public $name;
  /**
   * Connector description (by front end user)
   *
   * @var string
   */
  public $description;
  /**
   *
   * @var int unsigned
   */
  public $connector_type_id;
  /**
   * Is this the default connector of this type for this domain?
   *
   * @var boolean
   */
  public $is_active;
  /**
   * Is this the default connector of this type for this domain?
   *
   * @var boolean
   */
  public $is_default;
  /**
   * Optional FK to Contact ID. Assume at some point might want per contact connectors
   *
   * @var int unsigned
   */
  public $contact_id;
  /**
   * Storage field 1 to be defined by connector type
   *
   * @var string
   */
  public $field1;
  /**
   * Storage field 2 to be defined by connector type
   *
   * @var string
   */
  public $field2;
  /**
   * Storage field 3 to be defined by connector type
   *
   * @var string
   */
  public $field3;
  /**
   * Storage field 4 to be defined by connector type
   *
   * @var string
   */
  public $field4;
  /**
   * Storage field 5 (longer) to be defined by connector type
   *
   * @var test
   */
  public $field5;
  /**
   * class constructor
   *
   * @return civicrm_connector
   */
  function __construct()
  {
    $this->__table = 'civicrm_connector';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns()
  {
    if (!self::$_links) {
      self::$_links = static ::createReferenceColumns(__CLASS__);
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'domain_id', 'civicrm_domain', 'id');
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'connector_type_id', 'civicrm_connector_type', 'id');
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'contact_id', 'civicrm_contact', 'id');
    }
    return self::$_links;
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Connector ID',
          'required' => true,
        ) ,
        'domain_id' => array(
          'name' => 'domain_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Domain ID') ,
          'description' => 'Optional FK to Domain ID',
          'required' => false,
          'FKClassName' => 'CRM_Core_DAO_Domain',
        ) ,
        'name' => array(
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Name') ,
          'description' => 'Connector name (by front end user)',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
        ) ,
        'description' => array(
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Description') ,
          'description' => 'Connector description (by front end user)',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'connector_type_id' => array(
          'name' => 'connector_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Connector Type ID') ,
          'required' => TRUE,
          'FKClassName' => 'CRM_Connectors_DAO_ConnectorType',
          'pseudoconstant' => array(
            'table' => 'civicrm_connector_type',
            'keyColumn' => 'id',
            'labelColumn' => 'name',
          ),
        ) ,
        'is_active' => array(
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Is this the default connector of this type for this domain?',
        ) ,
        'is_default' => array(
          'name' => 'is_default',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Is this the default connector of this type for this domain?',
        ) ,
        'contact_id' => array(
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contact ID') ,
          'description' => 'Optional FK to Contact ID. Assume at some point might want per contact connectors',
          'required' => false,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ) ,
        'field1' => array(
          'name' => 'field1',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field1') ,
          'description' => 'Storage field 1 to be defined by connector type',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field2' => array(
          'name' => 'field2',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field2') ,
          'description' => 'Storage field 2 to be defined by connector type',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field3' => array(
          'name' => 'field3',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field3') ,
          'description' => 'Storage field 3 to be defined by connector type',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field4' => array(
          'name' => 'field4',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Field4') ,
          'description' => 'Storage field 4 to be defined by connector type',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
        ) ,
        'field5' => array(
          'name' => 'field5',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Field5') ,
          'description' => 'Storage field 5 (longer) to be defined by connector type',
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'domain_id' => 'domain_id',
        'name' => 'name',
        'description' => 'description',
        'connector_type_id' => 'connector_type_id',
        'is_active' => 'is_active',
        'is_default' => 'is_default',
        'contact_id' => 'contact_id',
        'field1' => 'field1',
        'field2' => 'field2',
        'field3' => 'field3',
        'field4' => 'field4',
        'field5' => 'field5',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['connector'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['connector'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
